name: Build Plugin
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install NDK 28
        run: |
          echo "y" | sdkmanager "ndk;28.0.13004108"
          echo "ndk.dir=$ANDROID_HOME/ndk/28.0.13004108" >> local.properties

      - name: Validate GradleW
        uses: gradle/actions/wrapper-validation@v3

      - name: Build
        run: |
          bash gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FOGLTLOGLES-RendererPlugin Build
          path: app/build/outputs/apk/release/

