name: Build Plugin
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install CCache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          override_cache_key: ccache-FOGLTLOGLES-RendererPlugin-cache

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28b

      - name: Validate GradleW
        uses: gradle/actions/wrapper-validation@v3

      - name: Build
        run: |
          bash gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FOGLTLOGLES-RendererPlugin Build
          path: app/build/outputs/apk/release/

